name: minfo
description: Minfo is a marketing application.

version: 7.0.8+708


environment:
  #sdk: ">=2.7.0 <3.0.0"
#  sdk: ">=2.7.0 <3.0.0"
  sdk: '>=2.12.0 <3.0.0'

#dependency_overrides:
#  firebase_core_platform_interface: 4.5.1

#  flutter_pdfview: 1.2.9
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

#  flutter_web_plugins:
  add_2_calendar: ^2.2.3 #2.1.0 #^1.4.0
  #  flutter_bloc: ^7.2.1 #7.0.0 #^5.0.1
  flutter_bloc: ^8.1.3 #7.0.0 #^5.0.1
  cached_network_image: ^3.2.3 #3.0.0 #^2.2.0+1 #onboard
  checkbox_grouped: ^1.8.2 #1.5.0
  cloud_firestore: ^4.7.1 #any
  cupertino_icons: ^1.0.5 #1.0.2 #^0.1.2
  dio: ^5.1.2 #^4.0.6 #4.0.0 #^3.0.10
  #  emoji_picker_flutter: ^1.0.6 #1.3.0 #1.0.6
  expressions: ^0.2.5 #0.2.2 #^0.1.5
  #  Analytics
  firebase_analytics: ^10.4.1 #8.0.3 #^6.2.0 #^7.0.1 #^6.2.0
  firebase_auth: ^4.6.1 #any
  firebase_core: ^2.13.0 #0.7.0 #^1.1.0 #^0.5.1 #^0.7.0 #^0.5.1
  firebase_crashlytics: ^3.3.1 #2.0.2 #^0.2.2 #^0.4.0+1 #^0.2.2
  #  dynamic links
  firebase_dynamic_links: ^5.3.1 #2.0.2 #^0.6.1 #^0.7.0+1 #^0.6.1
  #  inapMessaging
  firebase_in_app_messaging: ^0.7.3+1 #0.5.0+2 #^0.2.2 #^0.3.0+1 #^0.2.2
  #  FCM
  firebase_messaging: ^14.6.1 #9.1.3 #^7.0.3 #^7.0.3
  #  firebase performance
  firebase_performance: ^0.9.2+1 #0.7.0+2 #0.4.2 #^0.5.0+1 #^0.4.2
  #  remote config
  firebase_remote_config: ^4.2.1 #0.11.0 #^0.6.0 #^0.4.2 #^0.6.0 #^0.4.2
  firebase_storage: ^11.2.1 #8.0.5 #any
  #  flutter_contacts: ^1.1.5
#  flutter_neumorphic: ^3.2.0 #3.1.0
  neumorphic_ui: ^1.0.0
  flutter_secure_storage: ^8.0.0 #4.2.0 #^3.3.1+1
  #  flutter_share_me: ^1.3.0 #1.1.4 #^0.9.1
  flutter_spinkit: ^5.2.0 #5.0.0 #^4.1.2+1
  flutter_staggered_grid_view: ^0.6.2 #0.4.0 #^0.3.2
  fluttertoast: ^8.2.2 #8.0.6 #^7.1.1
  font_awesome_flutter: ^10.4.0 #9.0.0 #^8.8.1
  gallery_saver: ^2.3.2 #2.1.0
  google_fonts: ^4.0.4 #2.0.0 #^1.1.0
  http: ^0.13.6 #0.13.3 #^0.12.1
  image: ^3.3.0 #3.0.2
  image_cropper: ^4.0.1 #1.3.1
  image_picker: ^0.8.7+5 #0.8.4+1 # #^0.6.2+1
  logging: ^1.2.0 #1.0.0
  permission_handler: ^10.2.0 #8.3.0 #8.1.6 #^4.0.0
  pretty_qr_code: ^2.0.3 #2.0.1
  provider: ^6.0.5 #6.0.0 #^4.3.2+2
  qr_mobile_vision: ^4.1.2 #^3.0.1 #3.0.0 #^2.0.0
  #  scratcher: ^2.2.1 #2.1.0
#  share: ^2.0.4  #2.0.1 #^0.6.5+3
  share_plus: ^7.0.0
  shared_preferences: ^2.1.1 #2.0.5 #^0.5.6
  sqflite: ^2.2.8+4 #2.0.0+3 #^1.2.0 #db
  tutorial_coach_mark: ^1.2.8 #1.0.0 #^0.5.1
  url_launcher: ^6.1.11 #^6.1.10 #^6.1.5 #6.0.3 #^5.4.1 #provided also by flutter_widget_from_html: ^0.3.2+1
  uuid: ^3.0.7 #3.0.1 #^3.0.4
  yaml: ^3.1.2 #3.1.0 #^2.2.1
  firebase_core_platform_interface: 4.8.0
  go_router: ^8.2.0
#  fastor_app_ui_widget: ^1.0.205


#  dart_jsonwebtoken: ^2.6.2
#  jwtson: ^1.0.7

  linkedin_login: ^2.2.1 #^1.3.1
  introduction_screen: ^3.1.8
  path_provider: ^2.0.15 #^2.0.1 #^1.6.0 #sqflite depend
  flutter_arc_text: ^0.5.0 #^0.3.1
  #  flutter_webview_plugin: ^0.4.0 #^0.3.11 #increased from 3.10+1
  webview_flutter: ^4.2.1 #^3.0.4 #^3.0.4
#  flutter_widget_from_html: ^0.13.0-alpha.1 # ^0.10.1 0.9.1  #^0.7.0 #^0.5.1+5 #^0.3.2+1
  flutter_html_v3: ^3.0.6
  universal_html: #^2.2.3 #2.2.2
  quill_html_editor: ^2.1.9
  video_player: ^2.6.1
  wakelock:
#  flutter_widget_from_html: ^0.10.1


  xml: ^6.2.2 #^5.3.1 #5.1.0 #^4.5.1
#  syncfusion_flutter_pdfviewer: ^21.1.41 #^19.1.59-beta
#  syncfusion_flutter_calendar: ^19.4.56 #19.1.65

#  flutter_pdfview: ^1.2.7
#  flutter_cached_pdfview: ^0.4.1
  flutter_cache_manager: ^3.3.0

  pdf_render: ^1.3.8

  signalr_core: ^1.1.1 #^1.0.6
  flutter_linkify: ^6.0.0 #^4.0.2
  #  webviewx: ^0.2.1
  qr_flutter: ^4.1.0
  flutter_barcode_scanner: ^2.0.0
  confetti: ^0.7.0 #^0.5.5
  flutter_shazam_kit: ^1.0.2
  prefs: ^4.0.0
  get_it: ^7.6.0
  flutter_timer_countdown: ^1.0.5
  date_format: ^2.0.7
  optimized_cached_image: ^3.0.1
  reorderable_grid_view: ^2.2.6
  percent_indicator: ^4.2.3
  file_picker: ^5.3.1
  flutter_colorpicker: ^1.0.3
  flex_color_picker: 
  dropdown_textfield: ^1.0.8
  dropdown_search: ^5.0.6
  searchfield: ^0.8.0
  get:
  # dynamic_form: ^0.23.0
  json_dynamic_form: 1.0.0
  intl: 
  # flutter_contact: 0.7.5+1

  audioplayers: 

  datetime_picker_formfield_new: ^2.1.0

  onscreen_num_keyboard: ^1.0.4

  modal_progress_hud_nsn:
  flutter_typeahead: ^4.4.0 #4.3.1 #^4.1.1

  scrollable_positioned_list: ^0.3.8  #0.1.10 #^0.1.8
  material_design_icons_flutter: ^7.0.7296 #^6.0.7096 #4.0.5955 #^3.4.4595
#  websocket_manager: ^0.2.2 #^0.2.2
#  websocket_manager_safe: ^0.2.3
  socket_io_client: ^2.0.2
#  auto_complete_search: ^0.0.4
#  flutter_contact: ^0.9.1+8 #^0.9.1+8 #0.8.1+2 #^0.6.5+1 #^0.8.1+2 #^0.6.5+1
  flutter_local_notifications: ^14.1.1 #4.0.0
  idb_sqflite: ^1.3.1
  pointer_interceptor: ^0.9.3+4
  dx_router: ^1.1.0
  uni_links: ^0.5.1

  #  audioplayers: ^4.0.1 #0.20.1 #^0.19.0 # #^0.14.0
#  image_downloader: ^0.31.0

  #  flutter_contact:
#    git:
#      url: https://github.com/kadersaka/flutter_contact_null_safety

  #UPGRADE library to nullesafety and reintegrate
  #  socket_io_common_client:
  #    git:
  #      url: https://github.com/kadersaka/socket_io_common_client



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  # test: any

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/appLogo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is

  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true


  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/game/
    - assets/appLogo.png
    - assets/assets/
    - assets/nonternet.png
    - assets/img/
    - pubspec.yaml
    - assets/ProfileImage/
    - assets/GroupImages/
    - assets/MediaShared/
    - assets/qrimages/
    - assets/
    - assets/chatheadIcon.png
    - assets/close.png
    - assets/closeBg.png
    - assets/notificationIcon.png
    - assets/teams.png
    - assets/zoom.png
    - assets/notconnecting/
    - assets/campaigns/
    - assets/row_icon_Images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Digitalnumbers
      fonts:
        - asset: assets/fonts/DigitalNumbers-Regular.ttf
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
